#!/usr/bin/env python3
"""Pre-Push & CI Verification Runner for MySunshine.

Runs flake8 linting (syntax, undefined names, style) and the pytest test suite.
Can also install itself as a Git pre-push hook.

Usage:
    python run_checks.py
    python run_checks.py --install-hook
"""

import argparse
import os
import subprocess
import sys


def print_step(title: str):
    print("\n" + "=" * 70)
    print(f"  --> {title}")
    print("=" * 70)


def print_success(msg: str):
    print(f"\033[92m[PASS] {msg}\033[0m")


def print_failure(msg: str):
    print(f"\033[91m[FAIL] {msg}\033[0m")


def run_command(cmd, desc: str) -> bool:
    print_step(desc)
    print(f"Command: {' '.join(cmd) if isinstance(cmd, list) else cmd}\n")
    res = subprocess.run(cmd)
    if res.returncode == 0:
        print_success(f"{desc} passed!")
        return True
    else:
        print_failure(f"{desc} failed with exit code {res.returncode}")
        return False


def install_git_hook():
    """Install this script as a Git pre-push hook."""
    hook_path = os.path.join(".git", "hooks", "pre-push")
    if not os.path.exists(".git"):
        print_failure("Not in a git repository root (.git directory not found).")
        return False

    hook_content = """#!/bin/sh
# Auto-generated by run_checks.py
echo "Running pre-push validation checks..."
python run_checks.py
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "\\n[PRE-PUSH HOOK BLOCKED] Fix the errors above before pushing.\\n"
    exit 1
fi
exit 0
"""
    try:
        os.makedirs(os.path.dirname(hook_path), exist_ok=True)
        with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(hook_content)

        # On Unix, make executable
        if os.name != "nt":
            os.chmod(hook_path, 0o755)

        print_success(f"Git pre-push hook installed successfully at {hook_path}")
        print("From now on, 'git push' will automatically run all lint and unit tests before pushing.")
        return True
    except Exception as e:
        print_failure(f"Failed to install git hook: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Run lint and test checks before pushing to Git.")
    parser.add_argument(
        "--install-hook",
        action="store_true",
        help="Install this script as a Git pre-push hook in .git/hooks/pre-push",
    )
    args = parser.parse_args()

    if args.install_hook:
        success = install_git_hook()
        sys.exit(0 if success else 1)

    print("\n" + "#" * 70)
    print("       MYSUNSHINE: PRE-PUSH VALIDATION SUITE")
    print("#" * 70)

    # 1. Critical Syntax & Undefined Names (flake8 E9, F63, F7, F82)
    step1_cmd = [
        sys.executable,
        "-m",
        "flake8",
        ".",
        "--count",
        "--select=E9,F63,F7,F82",
        "--show-source",
        "--statistics",
        "--exclude=.venv,venv,node_modules",
    ]
    if not run_command(step1_cmd, "Step 1: Flake8 Syntax & Undefined Name Check"):
        sys.exit(1)

    # 2. General Code Quality / Warnings
    step2_cmd = [
        sys.executable,
        "-m",
        "flake8",
        ".",
        "--count",
        "--exit-zero",
        "--max-complexity=10",
        "--max-line-length=120",
        "--statistics",
        "--exclude=.venv,venv,node_modules",
    ]
    run_command(step2_cmd, "Step 2: Flake8 Style & Complexity (Advisory)")

    # 3. Pytest Test Suite
    step3_cmd = [
        sys.executable,
        "-m",
        "pytest",
        "tests/",
        "-v",
    ]
    if not run_command(step3_cmd, "Step 3: Pytest Automated Unit & Multi-Resolution Test Suite"):
        sys.exit(1)

    print("\n" + "#" * 70)
    print_success("ALL PRE-PUSH CHECKS PASSED! Ready to push safely.")
    print("#" * 70 + "\n")
    sys.exit(0)


if __name__ == "__main__":
    main()
